# Generated by Django 5.2.6 on 2025-09-19 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[(' Verbal Harassment', 'Verbal Harassment'), ('Physical Assault', 'Physical Assault'), ('Workplace Discrimination', 'Workplace Discrimination'), ('Online Hate Speech', 'Online Hate Speech')], max_length=50)),
                ('incident_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved')], default='Submitted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
