# Generated by Django 5.2.6 on 2025-09-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('QURAN', 'Quranic Verse'), ('HADITH', 'Hadith'), ('ARTICLE', 'Article'), ('BIOGRAPHY', 'Historical Figure'), ('PROPHET', "Prophet's Life Lesson")], default='ARTICLE', max_length=10)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, help_text="e.g., Quran 49:13, Bukhari, or author's name", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
