# Generated by Django 5.2.6 on 2025-09-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_latitude_report_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='incident_datetime',
            field=models.DateTimeField(help_text='Please use the format: YYYY-MM-DD HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='report',
            name='incident_type',
            field=models.CharField(choices=[('Verbal Harassment', 'Verbal Harassment'), ('Physical Assault', 'Physical Assault'), ('Workplace Discrimination', 'Workplace Discrimination'), ('Online Hate Speech', 'Online Hate Speech')], max_length=50),
        ),
    ]
