# Generated by Django 5.2.6 on 2025-09-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_latitude_alter_report_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_approved_for_map',
            field=models.BooleanField(db_index=True, default=False, help_text='If checked, this report will appear on the public heatmap.', verbose_name='Approved for Map'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_contacted',
            field=models.BooleanField(default=False, verbose_name='Contacted Submitter'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_info_verified',
            field=models.BooleanField(default=False, verbose_name='Information Verified'),
        ),
    ]
