# Generated by Django 5.2.6 on 2025-09-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_is_approved_for_map_report_is_contacted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_contacted',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_info_verified',
        ),
        migrations.AlterField(
            model_name='report',
            name='is_approved_for_map',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
