# Generated by Django 5.2.6 on 2025-09-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_report_is_contacted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='severity_level',
            field=models.IntegerField(db_index=True, default=1, help_text='1=Low, 2=Medium, 3=High'),
        ),
    ]
