# Generated by Django 5.2.6 on 2025-09-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_severity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('telegram', 'Telegram')], max_length=10, null=True),
        ),
    ]
